### ISSUE TITLE
nuget installation error for version 1.1.5

### ISSUE THREAD

**Issue by kkbajaj** [Asido/EpubSharp#5]
Trying to install via nuget a receive the following error

Install-Package : Could not install package 'EpubSharp.dll 1.1.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package EpubSharp.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by Asido** [comment]
It's because the minimum .NETFramework,Version=v4.5.1
