### ISSUE TITLE
Share code to display epub in wpf web browser control?

### ISSUE THREAD

**Issue by NvVijayakumara** [Asido/EpubSharp#6]
Hi, I want to use your library in one of my wpf application. Can you share code to display epub in wpf web browser control.. please ?

**Comment by Asido** [comment]
This library is not for rendering `.epub` files. You can load a HTML file, but you will need some JavaScript to navigate the rendered content. Try to look at [futurepress/epub.js](https://github.com/futurepress/epub.js/) instead. I use it in [lingole.com](https://www.lingole.com/) to render `.epub`, while `EpubSharp` is used on the backend to serve the `.epub` archive files.
